name: Deploy Laravel via FTP

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PHP and Composer
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'  # Laravel 12 and your lock file requires PHP 8.2+
        extensions: mbstring, bcmath, xml, curl, mysql
        tools: composer

    - name: Install Composer dependencies
      run: composer install --no-dev --optimize-autoloader

    - name: Prepare deployment directory
      run: |
        rm -rf tests
        rm -rf .github
        rm -rf node_modules
        rm -f composer.lock composer.json

    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: ${{ secrets.FTP_PORT }}
        local-dir: ./
        server-dir: public_html/future-connect-api/
        exclude: |
          .git*
          node_modules
          tests
          .github
          composer.json
          composer.lock
          .env
          storage/debugbar
          storage/*.key
          storage/framework/cache/data
          storage/framework/sessions
          storage/framework/views
          storage/logs
